### ISSUE TITLE
Newletter Subscription Error

### ISSUE THREAD

**Issue by sm2x** [tastyigniter/ti-ext-frontend#5]
**Version 3.0.4-beta.24.2**

Entering a valid email on "Subscribe to our newsletter" throws:

![newsletter-box-click-error](https://user-images.githubusercontent.com/6595333/98710220-557dd380-23be-11eb-86c0-1cc1d1c5e5b6.png)

If you leave it blank and just click the send icon:

![newsletter-blankbox-click-error](https://user-images.githubusercontent.com/6595333/98710406-91189d80-23be-11eb-80be-b7edeb1ea85e.png)

**Comment by sampoyigi** [comment]
Fixed 9a2159a631f890d7c3ae63d7078802f4c6bed137

**Comment by sm2x** [comment]
1.  with valid email address:  OK
2.  clicking send leaving email-address blank:  Not OK,  still throwing lengthy error message.
